import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";
import profilepic from "../../public/images/profile/developer-pic-2.png";
import Image from "next/image";
import Skill from "@/components/Skill";
import Experience from "@/components/Experience";
import Transitions from "@/components/Transitions";
import { motion } from "framer-motion";

const About = () => {
  return (
    <>
      <Head>
        <title>ROHAN PRASAD GUPTA | About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />

      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-10">
          <AnimatedText
            text="Building Thoughtful Software With Impact."
            className="mb-16 md:mb-12 md:text-center text-5xl lg:text-6xl sm:!text-4xl xs:!text-3xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-primary via-purple to-primaryDark"
          />

          {/* Hero Split */}
          <section className="grid grid-cols-12 gap-12 md:gap-8 sm:gap-6 items-start">
            {/* Text */}
            <div className="col-span-7 xl:col-span-7 lg:col-span-12 order-1 flex flex-col gap-6">
              <h2 className="text-sm tracking-wider font-semibold uppercase text-dark/60 dark:text-light/60">
                About Me
              </h2>
              <p className="text-sm md:text-[15px] leading-relaxed text-dark/80 dark:text-light/75">
                I’m{" "}
                <span className="font-semibold text-dark dark:text-light">
                  Rohan Prasad Gupta
                </span>
                , a software developer crafting scalable, user‑centric
                applications across web platforms & emerging systems. With a
                Master’s in <strong>AI & IoT</strong> and hands‑on experience at{" "}
                <strong>RV Connex (Cynclair)</strong>, I bridge modern frontend
                engineering with robust backend & cloud practices.
              </p>
              <p className="text-sm md:text-[15px] leading-relaxed text-dark/80 dark:text-light/75">
                My toolkit spans{" "}
                <strong>
                  TypeScript, Next.js, React, Node.js, GraphQL, AWS, DevOps
                  workflows
                </strong>{" "}
                and data‑driven problem solving. I enjoy shaping maintainable
                architectures, elevating developer experience, and translating
                complexity into simple, resilient interfaces.
              </p>
              <p className="text-sm md:text-[15px] leading-relaxed text-dark/80 dark:text-light/75">
                Beyond code, I value clarity, knowledge sharing, and iterative
                refinement. I’ve mentored in academic settings, explored applied
                AI, and built products that emphasize performance,
                accessibility, and purposeful UX.
              </p>

              {/* Focus Areas */}
              <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-dark/55 dark:text-light/60 mb-3">
                  Focus Areas
                </h3>
                <ul className="flex flex-wrap gap-2">
                  {[
                    "Full‑Stack Engineering",
                    "Design Systems",
                    "Real‑Time Apps",
                    "Cloud & DevOps",
                    "AI Integration",
                    "Data Visualization",
                    "API Architecture",
                    "Performance",
                  ].map((tag) => (
                    <li
                      key={tag}
                      className="text-[11px] font-medium px-2.5 py-1 rounded-full bg-dark/5 dark:bg-light/10 text-dark/70 dark:text-light/70 border border-dark/10 dark:border-light/10 backdrop-blur-sm"
                    >
                      {tag}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Photo & Stats */}
            <div className="col-span-5 xl:col-span-5 lg:col-span-12 order-2 flex flex-col gap-8">
              <div className="relative group w-full max-w-md mx-auto">
                <div className="absolute -inset-2 rounded-2xl bg-gradient-to-br from-primary/50 via-purple/40 to-primaryDark/50 blur opacity-60 group-hover:opacity-80 transition" />
                <div className="relative rounded-2xl overflow-hidden border border-black/10 dark:border-light/10 bg-white/60 dark:bg-dark/60 backdrop-blur-sm shadow-md">
                  <Image
                    src={profilepic}
                    alt="Portrait of Rohan Prasad Gupta"
                    className="w-full h-auto object-cover"
                    priority
                    sizes="(max-width:768px) 100vw, (max-width:1200px) 40vw, 33vw"
                  />
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4 md:gap-3 w-full max-w-md mx-auto">
                {[
                  { label: "Projects", value: "10+" },
                  { label: "Skills", value: "18+" },
                  { label: "Years Learning", value: "5+" },
                ].map((card) => (
                  <motion.div
                    key={card.label}
                    whileHover={{ y: -4 }}
                    className="flex flex-col items-center justify-center rounded-xl bg-white/60 dark:bg-dark/60 backdrop-blur border border-black/10 dark:border-light/10 px-2 py-4 shadow-sm"
                  >
                    <span className="text-xl font-bold text-dark dark:text-light">
                      {card.value}
                    </span>
                    <span className="mt-1 text-[11px] font-medium tracking-wide text-dark/60 dark:text-light/60 text-center">
                      {card.label}
                    </span>
                  </motion.div>
                ))}
              </div>
            </div>
          </section>
          {/* Craft Philosophy section removed as requested */}

          {/* Skills & Experience */}
          <Skill />
          <Experience />
        </Layout>
      </main>
    </>
  );
};

export default About;
