import Transitions from "@/components/Transitions";
import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import Banner from "@/components/Banner";

const ContactMe = () => {
  const [nameText, setNameText] = useState("");
  const [emailText, setEmailText] = useState("");
  const [msgText, setMsgText] = useState("");
  const [bannerVisible, setBannerVisible] = useState(false);
  const [bannerMessage, setBannerMessage] = useState("");
  const [isSending, setIsSending] = useState(false);
  const isFormReady =
    Boolean(nameText.trim()) &&
    Boolean(emailText.trim()) &&
    Boolean(msgText.trim());

  const showBanner = (message) => {
    setBannerMessage(message);
    setBannerVisible(true);

    setTimeout(() => {
      setBannerVisible(false);
      setBannerMessage("");
    }, 3000);
  };

  const sendEmail = async (e) => {
    e.preventDefault();

    if (!nameText.trim() || !emailText.trim() || !msgText.trim()) {
      showBanner("Please fill in all fields.");
      return;
    }

    setIsSending(true);

    try {
      const response = await fetch("/api/contact", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: nameText,
          email: emailText,
          message: msgText,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data?.message || "Unable to send message.");
      }

      setNameText("");
      setEmailText("");
      setMsgText("");
      showBanner("Email sent successfully!");
    } catch (error) {
      showBanner(error.message || "Email sending failed.");
    } finally {
      setIsSending(false);
    }
  };

  return (
    <>
      <Head>
        <title>ROHAN PRASAD GUPTA | Contact page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <main className="w-full min-h-screen px-6 py-10 md:px-4">
        {bannerVisible && <Banner message={bannerMessage} />}

        <section className="w-full max-w-6xl mx-auto mt-16 md:mt-10">
          <div className="rounded-3xl border border-white/35 bg-white/10 backdrop-blur-xl p-8 shadow-2xl md:p-5">
            <div className="mb-8 text-center md:mb-6">
              <h1 className="text-5xl font-bold text-white drop-shadow-lg md:text-3xl">
                Let&apos;s Build Something Great
              </h1>
              <p className="mt-3 text-white/85 text-lg md:text-sm">
                Send me your idea, requirement, or collaboration request and I will get back to you.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-8 md:grid-cols-1">
              <div className="rounded-2xl border border-white/30 bg-white/15 p-6 shadow-xl">
                <p className="text-white text-2xl font-semibold md:text-xl">
                  Direct Contact
                </p>
                <p className="text-white/80 mt-2 text-sm">
                  Prefer email or call? Reach me directly using the details below.
                </p>

                <div className="mt-6 space-y-4">
                  <div className="rounded-xl bg-black/20 border border-white/20 px-4 py-3">
                    <p className="text-white/70 text-xs uppercase tracking-wider">Email</p>
                    <Link
                      href="mailto:rohanprasadgupta4@gmail.com"
                      target={"_blank"}
                      className="text-white text-sm underline underline-offset-2 break-all"
                    >
                      rohanprasadgupta4@gmail.com
                    </Link>
                  </div>

                  <div className="rounded-xl bg-black/20 border border-white/20 px-4 py-3">
                    <p className="text-white/70 text-xs uppercase tracking-wider">Phone</p>
                    <Link
                      href="tel:+660640701050"
                      className="text-white text-sm underline underline-offset-2"
                    >
                      +66 064 070 1050
                    </Link>
                  </div>

                  <div className="rounded-xl bg-black/20 border border-white/20 px-4 py-3">
                    <p className="text-white/70 text-xs uppercase tracking-wider">Location</p>
                    <p className="text-white text-sm">Rangsit, Thailand</p>
                  </div>
                </div>

                <p className="text-white/70 text-sm mt-6">
                  Open to freelance projects, full-time opportunities, and technical collaborations.
                </p>
              </div>

              <div className="rounded-2xl border border-white/30 bg-white/15 p-6 shadow-xl">
                <p className="text-white text-2xl font-semibold md:text-xl">Send a Message</p>
                <p className="text-white/80 mt-2 text-sm">
                  Fill all fields to enable the send button.
                </p>

                <form onSubmit={sendEmail} className="flex flex-col mt-5">
                  <label className="text-white/90 text-sm font-semibold mb-2">Name</label>
                  <input
                    type="text"
                    name="name"
                    placeholder="Your Name"
                    className="p-3 text-white placeholder:text-white/50 bg-black/25 border border-white/25 rounded-xl focus:outline-none focus:ring-2 focus:ring-cyan-300/60"
                    value={nameText}
                    onChange={(e) => setNameText(e.target.value)}
                    required
                  />

                  <label className="text-white/90 text-sm font-semibold mb-2 mt-4">Email</label>
                  <input
                    type="email"
                    name="email"
                    placeholder="you@example.com"
                    className="p-3 text-white placeholder:text-white/50 bg-black/25 border border-white/25 rounded-xl focus:outline-none focus:ring-2 focus:ring-cyan-300/60"
                    value={emailText}
                    onChange={(e) => setEmailText(e.target.value)}
                    required
                  />

                  <label className="text-white/90 text-sm font-semibold mb-2 mt-4">Message</label>
                  <textarea
                    name="message"
                    placeholder="Tell me about your project..."
                    className="p-3 min-h-[140px] text-white placeholder:text-white/50 bg-black/25 border border-white/25 rounded-xl focus:outline-none focus:ring-2 focus:ring-cyan-300/60"
                    value={msgText}
                    onChange={(e) => setMsgText(e.target.value)}
                    required
                  />

                  <button
                    type="submit"
                    disabled={isSending || !isFormReady}
                    className="mt-6 w-full rounded-xl border border-white/40 bg-white/15 py-3 text-lg font-semibold text-white transition hover:bg-white/30 disabled:cursor-not-allowed disabled:opacity-60"
                  >
                    {isSending ? "Sending..." : "Send Message"}
                  </button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default ContactMe;
