import React, { useRef } from "react";
import { motion, useScroll } from "framer-motion";
import LiIcon from "../components/LiIcon";
import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import Transitions from "@/components/Transitions";

const Details = ({ title, place, time, organization, score }) => {
  const ref = useRef(null);
  return (
    <li className="my-8 first:mt-0 last:mb-0 w-[60%] lg:w-[70%] md:w-[85%] sm:w-full px-2 mx-auto flex flex-col item-start justify-between">
      <LiIcon reference={ref} />
      <motion.div
        initial={{ y: 50 }}
        whileInView={{ y: 0 }}
        transition={{ duration: 1, type: "keyframes" }}
      >
        <h3 className="capitalize font-bold text-2xl md:text-xl sm:text-lg text-dark dark:text-light ">
          {title}
        </h3>
        <span className="capitalize text-primary dark:text-primaryDark font-semibold text-sm sm:text-xs">
          {time} | {organization}
        </span>
        <p className="text-sm w-full text-dark/70 dark:text-light/70">
          {place}
        </p>
        <span className="text-xs w-full font-semibold text-dark/60 dark:text-light/60">
          {score}
        </span>
      </motion.div>
    </li>
  );
};

const Education = () => {
  const ref = useRef(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "center start"],
  });

  return (
    <>
      <Head>
        <title>ROHAN PRASAD GUPTA | Education page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-10">
          <div className="items-center">
            <AnimatedText
              text="Education"
              className="font-bold text-7xl text-center w-full mb-16 sm:text-5xl md:text-6xl md:my-10 xs:text-4xl text-dark dark:text-light"
            />

            <div
              ref={ref}
              className="w-[75%] mx-auto relative lg:w-[80%] md:w-[90%] sm:w-full"
            >
              <motion.div
                style={{ scaleY: scrollYProgress }}
                className="bg-dark/70 dark:bg-light/70 origin-top w-[3px] h-full left-3 md:left-4 absolute top-1"
              />

              <ul>
                <Details
                  title="Master's Degree in artificial intelligence and IoT"
                  time="[2022 - 2024]"
                  organization="Sirindhorn International Institute of Technology (SIIT) [Thammasat University]"
                  place="Pathum Thani 12120, THAILAND"
                  score="GPA:&nbsp;3.76"
                />

                <Details
                  title="Bachelor of Technology in Computer Science Engineering"
                  time="[2016 - 2020]"
                  organization="Guru Nanak Institute of Technical Campus (GNITC) [JNTUH]"
                  place="Hyderabad, INDIA"
                  score="GPA:&nbsp;7.77"
                />

                <Details
                  title="Higher Secondary School"
                  time="[2014 - 2016]"
                  organization="Liverpool International Higher Secondary School"
                  place="Kathmandu, NEPAL"
                />

                {/* <Details
                  title="Secondary School"
                  time="[2013 - 2014]"
                  organization="New English Boarding School"
                  place="Janakpur, NEPAL"
                /> */}
              </ul>
            </div>
            <AnimatedText
              text="Learning compounds – foundation empowers innovation."
              className="mt-28 text-dark/70 dark:text-light/70 md:mt-16 xs:mt-16 sm:mt-16"
            />
          </div>
        </Layout>
      </main>
    </>
  );
};

export default Education;
