import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilepic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow, GithubIcon, LinkedInIcon } from "@/components/Icons";
import Transitions from "@/components/Transitions";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>ROHAN PRASAD GUPTA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <main className="relative flex w-full flex-col">
        <Layout className="relative overflow-hidden pt-4 md:pt-8">
          {/* Decorative gradient background blob */}
          <div className="pointer-events-none absolute -top-24 right-[-10%] h-[500px] w-[500px] rounded-full bg-gradient-to-br from-primary/30 via-primaryDark/30 to-purple/30 blur-3xl opacity-40 dark:opacity-30" />
          <div className="pointer-events-none absolute bottom-[-10%] left-[-10%] h-[420px] w-[420px] rounded-full bg-gradient-to-tr from-purple/30 via-primary/20 to-primaryDark/30 blur-3xl opacity-40 dark:opacity-25" />

          <div className="mx-auto grid max-w-7xl grid-cols-12 gap-12 lg:gap-10 md:gap-8 items-center">
            {/* Text Column */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="col-span-7 lg:col-span-12 order-2 lg:order-1"
            >
              <div className="mb-5 flex flex-wrap gap-2 text-[11px] font-medium tracking-wide">
                {[
                  "AI & IoT",
                  "Full‑Stack Dev",
                  "Cloud & Data",
                  "Research Driven",
                ].map((tag) => (
                  <span
                    key={tag}
                    className="rounded-full bg-dark/80 text-light px-3 py-1 dark:bg-light/90 dark:text-dark shadow-soft backdrop-blur-sm"
                  >
                    {tag}
                  </span>
                ))}
              </div>
              <AnimatedText
                text="Building Seamless Intelligent Experiences"
                className="!text-left text-5xl font-extrabold leading-tight tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-primary via-purple to-primaryDark xl:!text-5xl lg:!text-5xl md:!text-4xl sm:!text-3xl"
              />
              <p className="mt-5 max-w-xl text-pretty text-base leading-relaxed text-dark/80 dark:text-light/70 md:text-sm">
                I’m a software developer with a Master’s in AI & IoT focused on
                designing resilient, human‑centered systems. I work across
                TypeScript, Next.js, Node, Python, and cloud platforms—bridging
                intelligent services with practical usability. I value
                performant architectures, clear DX, and incremental innovation
                shipped with quality.
              </p>
              <div className="mt-8 flex flex-wrap items-center gap-4">
                <Link
                  href="/dummyCV.pdf"
                  target="_blank"
                  download
                  className="group inline-flex items-center gap-2 rounded-full bg-dark px-6 py-3 text-sm font-semibold text-light shadow-soft transition hover:-translate-y-0.5 hover:bg-dark/90 dark:bg-light dark:text-dark dark:hover:bg-light/90"
                >
                  Download CV
                  <LinkArrow className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
                </Link>
                <Link
                  href="mailto:rohanprasadgupta4@gmail.com"
                  className="inline-flex items-center rounded-full border border-dark/30 px-6 py-3 text-sm font-medium text-dark backdrop-blur hover:bg-dark/5 dark:border-light/30 dark:text-light dark:hover:bg-light/10"
                >
                  Contact
                </Link>
                <Link
                  href="https://github.com/RohanPrasadGupta"
                  target="_blank"
                  aria-label="GitHub"
                  className="inline-flex h-11 w-11 items-center justify-center rounded-full border border-dark/20 bg-white/60 text-dark shadow-sm backdrop-blur transition hover:bg-white dark:border-light/20 dark:bg-dark/60 dark:text-light dark:hover:bg-dark/70"
                >
                  <GithubIcon className="h-5 w-5" />
                </Link>
                <Link
                  href="https://www.linkedin.com/in/rohanprasadgupta"
                  target="_blank"
                  aria-label="LinkedIn"
                  className="inline-flex h-11 w-11 items-center justify-center rounded-full border border-dark/20 bg-white/60 text-dark shadow-sm backdrop-blur transition hover:bg-white dark:border-light/20 dark:bg-dark/60 dark:text-light dark:hover:bg-dark/70"
                >
                  <LinkedInIcon className="h-5 w-5" />
                </Link>
              </div>
              <div className="mt-10 flex flex-wrap gap-8 text-center md:gap-6">
                {[
                  { label: "Projects", value: "10+" },
                  { label: "Skills", value: "18+" },
                  { label: "Collaboration", value: "Open" },
                ].map((stat) => (
                  <div key={stat.label} className="min-w-[90px]">
                    <div className="text-3xl font-bold text-dark dark:text-light md:text-2xl">
                      {stat.value}
                    </div>
                    <div className="mt-1 text-xs tracking-wide text-dark/60 dark:text-light/50">
                      {stat.label}
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Image Column */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6, delay: 0.15 }}
              className="relative col-span-5 lg:col-span-8 lg:mx-auto order-1 lg:order-2 md:col-span-10"
            >
              <div className="relative mx-auto w-full max-w-md">
                <div className="absolute -inset-2 rounded-3xl bg-gradient-to-tr from-primary/50 via-purple/40 to-primaryDark/40 blur-xl opacity-60" />
                <div className="relative overflow-hidden rounded-3xl border border-light/60 bg-white/60 p-2 shadow-xl backdrop-blur dark:border-dark/60 dark:bg-dark/60">
                  <Image
                    src={profilepic}
                    alt="Portrait of Rohan Prasad Gupta"
                    className="h-auto w-full rounded-2xl object-cover"
                    priority
                    sizes="(max-width:768px) 100vw, (max-width:1200px) 40vw, 40vw"
                  />
                </div>
              </div>
            </motion.div>
          </div>
        </Layout>
      </main>
    </>
  );
}
