import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilepic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>ROHAN PRASAD GUPTA</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex item-center text-dark w-full min-h-hscreen'>
        <Layout className='pt-0'>
          <div className="flex item-center justify-between w-full">
            <div className='w-1/2'>
              <Image src ={profilepic} alt='ROHAN' className ='w-full h-auto '/>
            </div>

            <div className='w-1/2 felx felx-col items-center self-center'>
              
                <AnimatedText text="[AI and IoT] Master's Degree student | Software Developer" className="!text-left"/>
              
              <p className="my-4 text-base font-medium">
              I am a computer science engineer currently pursuing a Master's degree in AI and IoT. With a strong foundation in programming languages like Python, SQL, and C, I have developed expertise in data analytics, visualization, and database management. Additionally, I have acquired skills in software programming, Microsoft Power Platform, and web development. I am also actively engaged in expanding my knowledge through online courses in artificial intelligence, data science, and machine learning. I am looking for an opportunity to work in a challenging environment that will help me grow as a professional and utilize my skills and abilities to the fullest.
              </p>

              <div className='flex item-center self-start mt-2'>
                <Link href='/dummyCV.pdf' target={'_blank'} className='flex item-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                download={true}>Resume <LinkArrow className={`w-6 ml-1`}/></Link>

                <Link href='mailto:rohanprasadgupta4@gmail.com' target={'_blank'} className='ml-4 text-lg my-2 font-medium capitalize text-dark underline'>Contact</Link>

              </div>
            </div>

          </div>
        </Layout>
      </main>
    </>
  )
}
